#!/usr/bin/env bash

#/ command: jupyter-ansible:run: "start"
#/ usage: rerun jupyter-ansible:run [options]
#/ rerun-variables: RERUN, RERUN_VERSION, RERUN_MODULES, RERUN_MODULE_DIR
#/ option-variables: 

. "$RERUN_MODULE_DIR/lib/functions.sh" "run" || { 
  echo >&2 "Failed loading function library." ; exit 1 ; 
}

set -o errexit -o nounset -o pipefail

rerun_options_parse "$@"

# Command implementation
# ----------------------
podman run --name jupyter-ansible -v /srv/jupyter/ansible:/home/jupyter/volume --rm --net host --security-opt apparmor=unconfined --user jupyter --workdir /home/jupyter/volume jupyter-ansible --ip=0.0.0.0
exit $?
