#!/usr/bin/env bash

#/ command: jupyter:local: "create local container"
#/ usage: rerun jupyter:local [options]
#/ rerun-variables: RERUN, RERUN_VERSION, RERUN_MODULES, RERUN_MODULE_DIR
#/ option-variables: 

. "$RERUN_MODULE_DIR/lib/functions.sh" "local" || { 
  echo >&2 "Failed loading function library." ; exit 1 ; 
}

set -o errexit -o nounset -o pipefail -o errtrace

rerun_options_parse "$@"

# Command implementation
# ----------------------
export NAME="jupyter-build"
export FROM="docker://docker.io/library/alpine:edge"
export OPTS=""
THIS="$RERUN_MODULE_DIR/commands/create"
. "$RERUN_MODULES/lib/functions.sh"
. "$RERUN_MODULES/lib/buildah.sh"
RUN /sbin/apk upgrade --no-cache --available --no-progress
RUN /sbin/apk add --no-cache --no-progress python3 zeromq
RUN /sbin/apk add --no-cache --no-progress --virtual build-dependencies build-base gcc python3-dev linux-headers zeromq-dev
RUN adduser -D jupyter
RUN python3 -m pip install --progress-bar off --upgrade pip
RUN su -l -c 'python3 -m pip install --progress-bar off --no-warn-script-location --user jupyter' jupyter
RUN /sbin/apk del build-dependencies
RUN rm -rf /var/cache/apk
CLEAR /tmp
ENTRYPOINT '["/home/jupyter/.local/bin/jupyter-notebook", "--no-browser"]'
COMMIT jupyter
print "jupyter:create OK"
exit $?
