#!/usr/bin/env bash

#/ command: securelink:local: "Create local SecureLink container"
#/ usage: rerun securelink:local [options]
#/ rerun-variables: RERUN, RERUN_VERSION, RERUN_MODULES, RERUN_MODULE_DIR
#/ option-variables:

. "$RERUN_MODULE_DIR/lib/functions.sh" "local" || {
  echo >&2 "Failed loading function library." ; exit 1 ;
}

set -o errexit -o nounset -o pipefail

rerun_options_parse "$@"

# Command implementation
# ----------------------

# - - -
# Put the command implementation here.
# - - -
NAME="securelink-build"
FROM="centos:7"
OPTS=""
. "$RERUN_MODULE_DIR/lib/buildah.sh"
YUM="/usr/bin/yum -y -q -e 0 --setopt=tsflags=nodocs"
PRINT "+C" "Updating CentOS..."
RUN $YUM install deltarpm
RUN $YUM update
PRINT "+C" "Adding rss user..."
RUN useradd -m -U -d /home/rss rss
RUN $YUM install glibc.i686
PRINT "+C" "Installing SecureLink..."
COPY jdaclient.tar.gz /
COPY jdajava.tar.gz /
RUN tar -C /home/rss -xf /jdaclient.tar.gz
RUN tar -C /home/rss -xf /jdajava.tar.gz
RUN rm -f /jdaclient.tar.gz
RUN rm -f /jdajava.tar.gz
PRINT "?C" "Enter SecureLink registration code:"
read code
SH "echo autoRegCode=$code > /home/rss/slink/bin/auto_install.properties"
RUN chown rss:rss /home/rss/slink/bin/auto_install.properties
CONFIG --entrypoint '["/home/rss/slink/java/bin/java", "-Djava.class.path=/home/rss/slink/lib/jettyslink.jar:/home/rss/slink/lib/jetty.jar:/home/rss/slink/lib/jetty-util.jar:/home/rss/slink/lib/servlet.jar", "-Djetty.home=/home/rss/slink", "-Dfile.encoding=UTF-8", "-Djava.security.egd=file:/dev/urandom", "rss.jettyslink.JettySLink", "/home/rss/slink/conf/jetty.xml"]'
CONFIG --cmd ''
CONFIG --stop-signal TERM
PRINT "+H" "Committing to containers-storage..."
buildah commit ${NAME} containers-storage:securelink
# Done. Exit with last command exit status.
exit $?

