#!/usr/bin/env bash

#/ command: securelink:service: "Create systemd unit"
#/ usage: rerun securelink:service [options]
#/ rerun-variables: RERUN, RERUN_VERSION, RERUN_MODULES, RERUN_MODULE_DIR
#/ option-variables:

. "$RERUN_MODULE_DIR/lib/functions.sh" "service" || {
  echo >&2 "Failed loading function library." ; exit 1 ;
}

set -o errexit -o nounset -o pipefail

rerun_options_parse "$@"

# Command implementation
# ----------------------

# - - -
# Put the command implementation here.
# - - -
function cleanup() {
    PRINT "+" "Deleting incomplete systemd unit..."
    rm -f "$SERVICE"
    systemctl daemon-reload
}
trap cleanup ERR
PRINT "+" "Getting image ID of SecureLink container..."
IMAGE=$(podman images | grep -F "securelink" | awk '{print $3}')
SERVICE="/etc/systemd/system/podman-securelink.service"
PRINT "+" "Generating systemd unit..."
cp "$RERUN_MODULE_DIR/commands/service/podman-securelink.service" $SERVICE
sed -i "s:__IMAGE__:$IMAGE:g" $SERVICE
PRINT "+" "Enabling and starting SecureLink container service..."
systemctl daemon-reload
systemctl enable podman-securelink
systemctl start podman-securelink
PRINT "+" "Checking if SecureLink container service is up..."
systemctl is-active podman-securelink
PRINT "!" "DONE."
# Done. Exit with last command exit status.
exit $?

