#!/usr/bin/env bash

#/ command: diceware:local: "Create container"
#/ usage: rerun diceware:local [options]
#/ rerun-variables: RERUN, RERUN_VERSION, RERUN_MODULES, RERUN_MODULE_DIR
#/ option-variables:

. "$RERUN_MODULE_DIR/lib/functions.sh" "local" || {
  echo >&2 "Failed loading function library." ; exit 1 ;
}

set -o errexit -o nounset -o pipefail -o errtrace

rerun_options_parse "$@"

# Command implementation
# ----------------------

# - - -
# Put the command implementation here.
# - - -
function cleanup {
    PRINT "+H" "Cleaning up..."
    buildah rm "$NAME" 2>/dev/null 1>/dev/null
    PRINT "+X" "Done!"
}
trap cleanup ERR
. "$RERUN_MODULES/lib/print.sh"
NAME="diceware-build"
FROM="docker.io/library/debian:stable-slim"
OPTS=""
. "$RERUN_MODULES/lib/buildah.sh"
APT_GET="/usr/bin/env DEBIAN_FRONTEND=noninteractive apt-get -qq"
MKDIR /usr/share/man/man1
MKDIR /usr/share/man/man7
RUN /usr/bin/touch /usr/share/man/man1/sh.distrib.1.gz
RUN $APT_GET update
RUN $APT_GET dist-upgrade
RUN $APT_GET --no-install-recommends install diceware
RUN $APT_GET --allow-remove-essential remove sysvinit-utils e2fsprogs e2fslibs
RUN $APT_GET clean
RUN $APT_GET autoremove
COPY "$RERUN_MODULE_DIR/commands/local/american-english-insane.txt" /usr/lib/python2.7/dist-packages/diceware/wordlists/wordlist_en_insane.txt
CLEAR /tmp
CLEAR /var/tmp
CLEAR /var/lib/apt/lists
CONFIG --entrypoint '["/usr/bin/diceware"]'
CONFIG --cmd ''
CONFIG --stop-signal TERM
PRINT "+H" "Committing to containers-storage..."
buildah commit --rm --squash "${NAME}" "containers-storage:diceware"
# Done. Exit with last command exit status.
exit $?
