#!/usr/bin/env bash

#/ command: jupyter-ansible:local: "create"
#/ usage: rerun jupyter-ansible:local [options]
#/ rerun-variables: RERUN, RERUN_VERSION, RERUN_MODULES, RERUN_MODULE_DIR
#/ option-variables: 

. "$RERUN_MODULE_DIR/lib/functions.sh" "local" || { 
  echo >&2 "Failed loading function library." ; exit 1 ; 
}

set -o errexit -o nounset -o pipefail -o errtrace

rerun_options_parse "$@"

# Command implementation
# ----------------------
export NAME="jupyter-ansible-build"
export FROM="docker://docker.io/library/alpine:edge"
export OPTS=""
THIS="$RERUN_MODULE_DIR/commands/create"
. "$RERUN_MODULES/lib/functions.sh"
. "$RERUN_MODULES/lib/buildah.sh"
BRUN="/usr/bin/buildah run ${__CONTAINER} --"
RUN /sbin/apk upgrade --no-cache --available --no-progress
RUN /sbin/apk add --no-cache --no-progress python3 zeromq git openssh-client bash sshpass
# DELETE according to PEP 594
# cgi, uu required by pip
# imp(py,c) required by tornado and ansible
# pipes required by pyzmq
# crypt required by ansible
${BRUN} rm -f /usr/lib/python3.7/{aifc,asynchat,asyncore,audioop,binhex,cgitb,chunk,formatter,fpectl}.py
${BRUN} rm -f /usr/lib/python3.7/{imghdr,macpath,msilib,nntplib,nis,ossaudiodev,parser,smtpd}.py
${BRUN} rm -f /usr/lib/python3.7/{sndhdr,spwd,sunau,xdrlib}.py
${BRUN} rm /usr/lib/python3.7/lib-dynload/{audioop,ossaudiodev,spwd,parser}.cpython-37m-x86_64-linux-gnu.so
RUN /sbin/apk add --no-cache --no-progress --virtual build-dependencies build-base gcc python3-dev linux-headers zeromq-dev libffi-dev openssl-dev
RUN adduser -D jupyter
RUN python3 -m pip install --progress-bar off --upgrade pip
RUN su -l -c 'python3 -m pip install --progress-bar off --no-warn-script-location --user jupyter jupyterlab' jupyter
RUN su -l -c 'python3 -m pip install --progress-bar off --no-warn-script-location --user jupyter-spaces nbstripout suitable' jupyter
RUN /sbin/apk del build-dependencies
RUN rm -rf /var/cache/apk
CLEAR /tmp
ENTRYPOINT '["/home/jupyter/.local/bin/jupyter-lab", "--no-browser"]'
COMMIT jupyter-ansible
print "jupyter-ansible:create OK"
exit $?
