#!/usr/bin/env bash

#/ command: tumbleweed:rootfs: "Create container image for custom openSUSE Tumbleweed rootfs"
#/ usage: rerun tumbleweed:rootfs [options]
#/ rerun-variables: RERUN, RERUN_VERSION, RERUN_MODULES, RERUN_MODULE_DIR
#/ option-variables:

. "$RERUN_MODULE_DIR/lib/functions.sh" "rootfs" || {
  echo >&2 "Failed loading function library." ; exit 1 ;
}

set -o errexit -o nounset -o pipefail -o errtrace

rerun_options_parse "$@"

# Command implementation
# ----------------------

# - - -
# Put the command implementation here.
# - - -
function remove_image {
    if podman inspect "tumbleweed-rootfs" 2>/dev/null 1>/dev/null
    then
        podman rmi -f $(podman images | grep -F -- 'tumbleweed-rootfs ' | awk '{print $3}')
    fi
}
export NAME="tumbleweed-build"
export FROM="docker.io/opensuse/tumbleweed"
export OPTS=""
. "$RERUN_MODULES/lib/print.sh"
. "$RERUN_MODULES/lib/buildah.sh"
PRINT "+H" "Removing old image..."
remove_image
RUN zypper dup -y
RUN zypper install --no-recommends -y systemd grub2 kernel-default kernel-firmware install-initrd-openSUSE glibc-locale grub2-x86_64-efi
RUN zypper install --no-recommends -y e2fsprogs xfsprogs nftables iproute2 openssh tmux git neovim podman buildah chrony apparmor-parser apparmor-profiles curl golang-github-prometheus-node_exporter tar which wget tcpdump strace opmsg rsync skopeo lvm2 xz ca-certificates netcat-openbsd
RUN zypper clean --all
CLEAR /tmp
CLEAR /var/tmp
PRINT "+H" "Committing to containers-storage..."
buildah commit --rm --squash "${NAME}" "containers-storage:tumbleweed-rootfs"
# Done. Exit with last command exit status.
exit $?
