#!/usr/bin/env bash

#/ command: postgresql:service: "Create systemd unit"
#/ usage: rerun postgresql:service [ --postgresql <"9.6">]
#/ rerun-variables: RERUN, RERUN_VERSION, RERUN_MODULES, RERUN_MODULE_DIR
#/ option-variables:

. "$RERUN_MODULE_DIR/lib/functions.sh" "service" || {
  echo >&2 "Failed loading function library." ; exit 1 ;
}

set -o errexit -o nounset -o pipefail -o errtrace

rerun_options_parse "$@"

# Command implementation
# ----------------------

# - - -
# Put the command implementation here.
# - - -
function cleanup() {
    PRINT "+" "Deleting incomplete systemd unit..."
    rm -f $SERVICE
    systemctl daemon-reload
}
trap cleanup ERR
PRINT "+" "Getting image ID of PostgreSQL ${POSTGRESQL} container..."
IMAGE=podman images | grep -F "postgresql-${POSTGRESQL}" | awk '{print $3}'
SERVICE="/etc/systemd/system/container-postgresql.service"
PRINT "+" "Generating systemd unit..."
cp "$RERUN_MODULE_DIR/postgresql/commands/service/container-postgresql.service" $SERVICE
sed -i "s:__IMAGE__:$IMAGE:g" $SERVICE
sed -i "s:__POSTGRESQL__:$POSTGRESQL:g" $SERVICE
PRINT "+" "Enabling and starting PostgreSQL container service..."
systemctl daemon-reload
systemctl enable container-postgresql
systemctl start container-postgresql

PRINT "DONE."

# Done. Exit with last command exit status.
exit $?

