#!/usr/bin/env bash

#/ command: samba:service: "start"
#/ usage: rerun samba:service [options]
#/ rerun-variables: RERUN, RERUN_VERSION, RERUN_MODULES, RERUN_MODULE_DIR
#/ option-variables: 

. "$RERUN_MODULE_DIR/lib/functions.sh" "service" || { 
  echo >&2 "Failed loading function library." ; exit 1 ; 
}

set -o errexit -o nounset -o pipefail -o errtrace

rerun_options_parse "$@"

# Command implementation
# ----------------------
. "$RERUN_MODULES/lib/functions.sh"
. "$RERUN_MODULES/lib/systemd.sh"
THIS="$RERUN_MODULE_DIR/commands/service"
SVC="podman:samba.service"
print "Stopping existing unit..."
unit_stop "$SVC"
print "Generating systemd unit..."
unit_install "$THIS/$SVC"
unit_image "samba" "$SVC"
print "Enabling and starting service..."
unit_start "$SVC"
print "Checking if container service is up..."
unit_active "$SVC"
print "DONE."
exit $?
